# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_client_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ClientWindow(object):
    def setupUi(self, ClientWindow):
        ClientWindow.setObjectName("ClientWindow")
        ClientWindow.resize(522, 301)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ClientWindow.sizePolicy().hasHeightForWidth())
        ClientWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(ClientWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.IP_input = QtWidgets.QLineEdit(self.centralwidget)
        self.IP_input.setObjectName("IP_input")
        self.horizontalLayout_4.addWidget(self.IP_input)
        self.Connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.Connect_button.setObjectName("Connect_button")
        self.horizontalLayout_4.addWidget(self.Connect_button)
        self.Disconnect_button = QtWidgets.QPushButton(self.centralwidget)
        self.Disconnect_button.setObjectName("Disconnect_button")
        self.horizontalLayout_4.addWidget(self.Disconnect_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ScreenCapture_button = QtWidgets.QPushButton(self.groupBox_3)
        self.ScreenCapture_button.setObjectName("ScreenCapture_button")
        self.verticalLayout_4.addWidget(self.ScreenCapture_button)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.processButton = QtWidgets.QPushButton(self.groupBox_6)
        self.processButton.setObjectName("processButton")
        self.verticalLayout_2.addWidget(self.processButton)
        self.appButton = QtWidgets.QPushButton(self.groupBox_6)
        self.appButton.setObjectName("appButton")
        self.verticalLayout_2.addWidget(self.appButton)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.System_button = QtWidgets.QPushButton(self.groupBox_2)
        self.System_button.setAutoFillBackground(False)
        self.System_button.setObjectName("System_button")
        self.verticalLayout.addWidget(self.System_button)
        self.Get_MAC_button = QtWidgets.QPushButton(self.groupBox_2)
        self.Get_MAC_button.setAutoFillBackground(False)
        self.Get_MAC_button.setObjectName("Get_MAC_button")
        self.verticalLayout.addWidget(self.Get_MAC_button)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.registryButton = QtWidgets.QPushButton(self.groupBox_7)
        self.registryButton.setObjectName("registryButton")
        self.verticalLayout_3.addWidget(self.registryButton)
        self.verticalLayout_6.addWidget(self.groupBox_7)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.File_Show_button = QtWidgets.QPushButton(self.groupBox_4)
        self.File_Show_button.setObjectName("File_Show_button")
        self.horizontalLayout_2.addWidget(self.File_Show_button)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Keyboard_show_button = QtWidgets.QPushButton(self.groupBox_5)
        self.Keyboard_show_button.setObjectName("Keyboard_show_button")
        self.horizontalLayout_3.addWidget(self.Keyboard_show_button)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addWidget(self.groupBox)
        ClientWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ClientWindow)
        QtCore.QMetaObject.connectSlotsByName(ClientWindow)

    def retranslateUi(self, ClientWindow):
        _translate = QtCore.QCoreApplication.translate
        ClientWindow.setWindowTitle(_translate("ClientWindow", "Client"))
        self.Connect_button.setText(_translate("ClientWindow", "Connect"))
        self.Disconnect_button.setText(_translate("ClientWindow", "Disconnect"))
        self.groupBox.setTitle(_translate("ClientWindow", "Functions"))
        self.groupBox_3.setTitle(_translate("ClientWindow", "Screenshot and Stream"))
        self.ScreenCapture_button.setText(_translate("ClientWindow", "Screen"))
        self.groupBox_6.setTitle(_translate("ClientWindow", "App and  Process"))
        self.processButton.setText(_translate("ClientWindow", "Process"))
        self.appButton.setText(_translate("ClientWindow", "App"))
        self.groupBox_2.setTitle(_translate("ClientWindow", "System"))
        self.System_button.setText(_translate("ClientWindow", "Power options"))
        self.Get_MAC_button.setText(_translate("ClientWindow", "Get MAC"))
        self.groupBox_7.setTitle(_translate("ClientWindow", "Registry"))
        self.registryButton.setText(_translate("ClientWindow", "Registry"))
        self.groupBox_4.setTitle(_translate("ClientWindow", "File Related"))
        self.File_Show_button.setText(_translate("ClientWindow", "File Explorer"))
        self.groupBox_5.setTitle(_translate("ClientWindow", "Keyboard Related"))
        self.Keyboard_show_button.setText(_translate("ClientWindow", "Keyboard Controller"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClientWindow = QtWidgets.QMainWindow()
    ui = Ui_ClientWindow()
    ui.setupUi(ClientWindow)
    ClientWindow.show()
    sys.exit(app.exec_())

