# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegistryGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QFileDialog

# from variables import *
from gui.popup import PopUp


class RegistryGUI(object):
# =============================================================================
#     def __init__(self, client):
#         super(RegistryGUI, self).__init__()
#         self.setupUi()
#         self.removed_option_item = False
#         self.client = client
# =============================================================================

    def setupUi(self, regUI):
        regUI.setObjectName("MainWindow")
        regUI.resize(800, 600)
        
        ###
        self.centralwidget = QtWidgets.QWidget(regUI)
        self.centralwidget.setObjectName("centralwidget")
        self.path_input = QtWidgets.QLineEdit(self.centralwidget)
        self.path_input.setGeometry(QtCore.QRect(20, 10, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.path_input.setFont(font)
        self.path_input.setObjectName("path_input")
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_button.setGeometry(QtCore.QRect(640, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.browse_button.setFont(font)
        self.browse_button.setObjectName("browse_button")
        self.file_data = QtWidgets.QTextEdit(self.centralwidget)
        self.file_data.setGeometry(QtCore.QRect(20, 60, 601, 111))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.file_data.setFont(font)
        self.file_data.setObjectName("file_data")
        self.send_file_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_file_data_button.setGeometry(QtCore.QRect(640, 60, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.send_file_data_button.setFont(font)
        self.send_file_data_button.setObjectName("send_file_data_button")
        self.change_property_label = QtWidgets.QLabel(self.centralwidget)
        self.change_property_label.setGeometry(QtCore.QRect(20, 190, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.change_property_label.setFont(font)
        self.change_property_label.setObjectName("change_property_label")
        self.options_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.options_combobox.setGeometry(QtCore.QRect(20, 220, 741, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.options_combobox.setFont(font)
        self.options_combobox.setObjectName("options_combobox")
        self.options_combobox.addItem("")
        self.options_combobox.addItem("")
        self.options_combobox.addItem("")
        self.options_combobox.addItem("")
        self.options_combobox.addItem("")
        self.options_combobox.addItem("")
        self.registry_path_input = QtWidgets.QLineEdit(self.centralwidget)
        self.registry_path_input.setGeometry(QtCore.QRect(20, 280, 741, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.registry_path_input.setFont(font)
        self.registry_path_input.setObjectName("registry_path_input")
        self.name_value_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_value_input.setGeometry(QtCore.QRect(20, 330, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.name_value_input.setFont(font)
        self.name_value_input.setObjectName("name_value_input")
        self.value_input = QtWidgets.QLineEdit(self.centralwidget)
        self.value_input.setGeometry(QtCore.QRect(170, 330, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.value_input.setFont(font)
        self.value_input.setObjectName("value_input")
        self.data_type_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.data_type_combobox.setGeometry(QtCore.QRect(310, 330, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.data_type_combobox.setFont(font)
        self.data_type_combobox.setObjectName("data_type_combobox")
        self.data_type_combobox.addItem("")
        self.data_type_combobox.addItem("")
        self.data_type_combobox.addItem("")
        self.data_type_combobox.addItem("")
        self.data_type_combobox.addItem("")
        self.data_type_combobox.addItem("")
        self.data_type_combobox.addItem("")
        self.result_textbox = QtWidgets.QTextEdit(self.centralwidget)
        self.result_textbox.setGeometry(QtCore.QRect(20, 380, 741, 121))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.result_textbox.setFont(font)
        self.result_textbox.setObjectName("result_textbox")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(140, 510, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.send_button.setFont(font)
        self.send_button.setObjectName("send_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(440, 510, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        ###
        regUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(regUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        
        regUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(regUI)
        self.statusbar.setObjectName("statusbar")
        
        regUI.setStatusBar(self.statusbar)

        self.retranslateUi(regUI)
        QtCore.QMetaObject.connectSlotsByName(regUI)

    def retranslateUi(self, regUI):
        _translate = QtCore.QCoreApplication.translate
        regUI.setWindowTitle(_translate("MainWindow", "Registry"))
        self.path_input.setPlaceholderText(_translate("MainWindow", "Path"))
        self.browse_button.setText(_translate("MainWindow", "Browse"))
        self.file_data.setPlaceholderText(_translate("MainWindow", "Content"))
        self.send_file_data_button.setText(
            _translate("MainWindow", "Send Content"))
        self.change_property_label.setText(_translate(
            "MainWindow", "Directly Change Registry Properties"))
        self.options_combobox.setItemText(
            0, _translate("MainWindow", "Options"))
        self.options_combobox.setItemText(
            1, _translate("MainWindow", "Get value"))
        self.options_combobox.setItemText(
            2, _translate("MainWindow", "Set value"))
        self.options_combobox.setItemText(
            3, _translate("MainWindow", "Delete value"))
        self.options_combobox.setItemText(
            4, _translate("MainWindow", "Create key"))
        self.options_combobox.setItemText(
            5, _translate("MainWindow", "Delete key"))
        self.registry_path_input.setPlaceholderText(
            _translate("MainWindow", "Path"))
        self.name_value_input.setPlaceholderText(
            _translate("MainWindow", "Name Value"))
        self.value_input.setPlaceholderText(_translate("MainWindow", "Value"))
        self.data_type_combobox.setItemText(
            0, _translate("MainWindow", "Data Types"))
        self.data_type_combobox.setItemText(
            1, _translate("MainWindow", "String"))
        self.data_type_combobox.setItemText(
            2, _translate("MainWindow", "Binary"))
        self.data_type_combobox.setItemText(
            3, _translate("MainWindow", "DWORD"))
        self.data_type_combobox.setItemText(
            4, _translate("MainWindow", "QWORD"))
        self.data_type_combobox.setItemText(
            5, _translate("MainWindow", "Multi-String"))
        self.data_type_combobox.setItemText(
            6, _translate("MainWindow", "Expandable String"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))