# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputButtonView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class InputButtonView(QMainWindow):
    def __init__(self, window_title, input_placeholder_text,
                 button_text, button_function):#, *button_funct_args):
        super(InputButtonView, self).__init__()
        self.window_title = window_title
        self.input_placeholder_text = input_placeholder_text
        self.button_text = button_text
        self.button_function = button_function
        self.setupUi()

    def setupUi(self):
        self.resize(502, 80)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.input_box = QtWidgets.QLineEdit(self.centralwidget)
        self.input_box.setGeometry(QtCore.QRect(10, 20, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.input_box.setFont(font)
        self.input_box.setObjectName("input_box")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(400, 20, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(9)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 502, 26))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.button.clicked.connect(
            lambda: self.button_function(self.input_box.text(),
                                         self))

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(self.window_title)
        self.input_box.setPlaceholderText(self.input_placeholder_text)
        self.button.setText(self.button_text)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    input_button_view = InputButtonView(
        "Kill process", "Enter process ID", "Kill", lambda: print("Hello World"))
    input_button_view.show()
    sys.exit(app.exec_())
